export const ADDLIVE = 'ADDLIVE'
export const REMLIVE = 'REMLIVE'
export const SENDTOORDER = 'SENDTOORDER'
export const REMALLLIVE = 'REMALLLIVE'

export const SENDTOBILL = 'SENDTOBILL'
export const REMALLORDER= 'REMALLORDER'
export const REMORDER = 'REMORDER'



export const ADVACEDOPTIONSSHOW = 'ADVACEDOPTIONSSHOW'
export const ADVACEDOPTIONSHIDE= 'ADVACEDOPTIONSHIDE'
export const ADDCUSTOMERSHOW = 'ADDCUSTOMERSHOW'
export const ADDCUSTOMERHIDE = 'ADDCUSTOMERHIDE'
export const OPENMODEL = 'OPENMODEL'
export const CLOSEMODEL = 'CLOSEMODEL'

export const BILLPAGESHOW = 'BILLPAGE'
export const BILLPAGEHIDE = 'BILLPAGEHIDE'
export const SETBILLID = 'SETBILLID'

export const ADDTABLEDATA = 'ADDTABLEDATA'


export const KOTORDER = 'KOTORDER'
export const KOTCART = 'KOTCART'
export const KOTITEM='KOTITEM'