import React from "react";
export const orderContext = React.createContext();
export const liveCartContext = React.createContext();
export const billContext = React.createContext();
export const billPageContext = React.createContext();
export const dispatchContext = React.createContext();
export const modalContext = React.createContext();
export const tableContext = React.createContext();
export const addCustomerContext = React.createContext();
export const EmployeeContext = React.createContext();
export const CustomerListContext = React.createContext();
